### ISSUE TITLE
Mod not working

### ISSUE THREAD

**Issue by INV-PLA** [JackFred2/EyeSpy#1]
[latest (3).log](https://github.com/JackFred2/EyeSpy/files/13445827/latest.3.log)
Example: 1.0.2+1.20.1

Translate the following paragraph into English, so that I can submit it to the author:

Expected behavior: The mod should be fully functional with all telescope features working properly. The commands should be configurable and function correctly.

To reproduce the issue: After launching the game, none of the telescope features are working. When attempting to modify the configuration file using commands, an error message is returned.

{
	/* Maximum range that pings and rangefinding will function at. This is capped by the world / server's render
	   distance.
	   Range: [16, 384]
	   Default: 256
	*/
	maxRangeBlocks: 256,
	/* Settings related to the pinging function added to spyglasses - to use, press the swap hands key,
	   default 'F'.
	*/
	ping: {
		/* Whether to enable the ping functionality for spyglasses.
		   Options: true, false
		   Default: true
		*/
		enabled: true,
		/* Whether pinging functionality requires the player to be zoomed in (using the spyglass), or if just having
		   it in their hand will suffice.
		   Options: true, false
		   Default: true
		*/
		requiresZoomIn: true,
		/* Maximum range of nearby players that will recieve the ping highlight and sound.
		   Range: [8, 256]
		   Default: 64
		*/
		notifyRangeBlocks: 64,
		/* Lifetime of ping highlights, in ticks.
		   Range: [60, 400] [3 seconds, 20 seconds]
		   Default: 160 (8 seconds)
		*/
		lifetimeTicks: 160,
	},
	/* Settings related to the rangefinding feature added to spyglasses - when looking at a block, or entity, the
	   distance will be displayed, as well as their names.
	*/
	rangefinder: {
		/* Whether to enable rangefinding functionality for spyglasses.
		   Options: true, false
		   Default: true
		*/
		enabled: true,
		/* Whether to use highlight colours for labels when looking at entities or blocks.
		   Options: true, false
		   Default: true
		*/
		useColours: true,
		/* Whether to show the name of the block being looked at, if applicable.
		   Options: true, false
		   Default: true
		*/
		showBlockName: true,
		/* Whether to show the name of the entity being looked at, if applicable.
		   Options: true, false
		   Default: true
		*/
		showEntityName: true,
	},
	// Users: do not edit manually! Last saved mod version
	"__version": "1.0.2+1.20.1",
}

**Comment by JackFred2** [comment]
I am unable to test right now, but I will have a look in the morning.

Meanwhile, from a quick look this appears to be a String encoding issue out of my control. Could you try removing the Chinese (Unicode) characters from the EyeSpy JAR filename? i.e:

`眼睛间谍eyespy-1.0.2+1.20.1.jar` -> `eyespy-1.0.2+1.20.1.jar`

**Comment by INV-PLA** [comment]
After this reboot,I do not know why it can be used,sorry to bother you

**Comment by JackFred2** [comment]
Glad you solved the problem. (If I've misread your reply, please reopen this issue.)
