### ISSUE TITLE
Ping doesn't update after its object's state changes (e.g. door opens/closes)

### ISSUE THREAD

**Issue by redactedscribe** [JackFred2/EyeSpy#10]
**Mod Version**
Example: 1.0.2+1.20.2

**Describe the bug**
See the screenshot below. With only one door it's not so confusing, but it could be in some scenarios. Ping also remains (until its timer expires) if the door is destroyed.

**Expected behavior**
Not sure what should/can happen once the object state changes. Perhaps reduce the opacity of the ping, or leave only its outline visible, or remove the ping completely?

Not tested without mods so it's possible something else is the cause.

**To Reproduce**
Ping door then open/close it.

**Screenshots (Optional)**

Opening door after pinging its top half:

![javaw_2023-12-09_15-55-35](https://github.com/JackFred2/EyeSpy/assets/25013746/31acf4cd-a534-495b-8dbe-19afe4307059)

Thanks!

**Comment by JackFred2** [comment]
Fixed in 1.2.0, there's a 1 tick lag to updating the ping but it's a non-issue.
