### ISSUE TITLE
Ping without spyglass in hand (or at all)

### ISSUE THREAD

**Issue by redactedscribe** [JackFred2/EyeSpy#12]
**Is your feature request related to a problem? Please describe.**

Must have spyglass to ping.

**Describe the solution you'd like**

For those that aren't interested in the more realistic experience of having a spyglass in hand or looking through it, allowing pinging at any time / any item in hand.

**Describe alternatives you've considered**

Learn to love the requirement.

Thanks.

**Comment by JackFred2** [comment]
added in 1.3.4; note you'll need to update both server and client and it's disabled by default; use `/eyespy config ping pingRequirement none`

**Comment by redactedscribe** [comment]
Thanks @JackFred2.
