### ISSUE TITLE
Ping `lifetimeTicks` config value as milliseconds instead of ticks

### ISSUE THREAD

**Issue by redactedscribe** [JackFred2/EyeSpy#13]
**Is your feature request related to a problem? Please describe.**

Must set `lifetimeTicks` as ticks. I don't know how long a tick is in time.

**Describe the solution you'd like**

Define value in milliseconds and Eye Spy round to nearest tick value under-the-hood.

**Describe alternatives you've considered**

Keep assuming everyone knows how ticks relate to time.

Thanks.

**Comment by JackFred2** [comment]
[Ticks](https://minecraft.wiki/w/Tick), in Minecraft's case, are by default 50 milliseconds, though they can fluctuate with e.g. server lag, or be set via the upcoming `/tick` command.
