### ISSUE TITLE
Incompatibility with immersive portals

### ISSUE THREAD

**Issue by iPauloLopes** [JackFred2/EyeSpy#2]
Mod Version
Fabric 1.0.2 - 1.20.1

Description
Game crashes the moment I zoom in with spyglasses. I'm using a lot of mods but disable immersive portals makes this mod works as intended. I suspected the issue was related to rangefinder and turned it off in the config file but when i pin something the game crashes.

To Reproduce
Install immersive portals and this mod. Enter any world and zoom in with a spyglass.

Config
I'm using default settings except for the rangefinder experiment described above. 

Crash Report
[crash-2023-11-27_09.54.04-server.txt](https://github.com/JackFred2/EyeSpy/files/13474545/crash-2023-11-27_09.54.04-server.txt)

**Comment by JackFred2** [comment]
Fixed crash for next release, but there are some quirks with the portals themselves:
- Rangefinding & pinging doesn't look through portals, but behind them (like the debug F3 selector on the right). I'd have to look into raycasting through portals.
- Glowing outlines don't render at all when a portal is being rendered anywhere on screen through another portal, or if the glowing entity is through a portal; pinging won't display anything. This I don't think I can fix on my end.

**Comment by JackFred2** [comment]
https://modrinth.com/mod/eye-spy/version/1.0.3+1.20.1
