### ISSUE TITLE
Port to 1.19.2

### ISSUE THREAD

**Issue by maiguel5** [JackFred2/EyeSpy#3]
**Is your feature request related to a problem? Please describe.**
I can't find a file for 1.19.2

**Describe the solution you'd like**
A versión to 1.19.2

**Additional context**
As you have a 1.19.4 version it should not be so far.

I see your mod as the best idea for the spyglass, but can't use in our actual server because we are running 1.19.2 as most mods were that version.

**Comment by JackFred2** [comment]
Unfortunately this is not really feasible; all of Eye Spy's features are built around [Display Entities](https://minecraft.wiki/w/Display), which were only added in 1.19.4.

**Comment by maiguel5** [comment]
Hi again!
First of all thanks for your time and response, it is sad to know, just readed what you linked.

Sorry if my english isn't perfect as i am not native, 
I don't want to be rude and this response is just to make you know that probably could be ported with some workaround as some mods in 1.19.2 have similar behavior to the features of Eye Spy (Anyway your mod does everything look pretty and fits better with the vanilla style)

Examples:
You can zoom in with: https://modrinth.com/mod/zoomify
You can measure distances and share positions with: https://modrinth.com/mod/instantmarker
You can find and make glow entitys with: https://legacy.curseforge.com/minecraft/mc-mods/witcher-medallions

Maybe you find in them an interesting way to do other nice features to Eye Spy's updates, backports or another future mod.

i will keep your work in track, greetings from Spain!

**Comment by JackFred2** [comment]
The important difference between those mods and Eye Spy is that Eye Spy is designed to work server-side only, without anything needed on the client. In comparison:

- Zoomify is a client-side-only mod for an Optifine-style zoom feature
- Instant Marker is a client-sided mod that chats to other players, with optional server-installed features
- Witcher Medallions is needed on both sides.

The Ping feature is definitely possible (an invisible glowing slime would work for block pings, though limited to the standard 16 colours and would fade out over long range), but I don't think the rangefinder is possible. 

It's just a case that a ground-up rewrite would be easier than trying to port the mod to before 1.19.4, and it would only have partial features.
