### ISSUE TITLE
Dedicated key for pinging (decouple from Swap Items With Offhand action)

### ISSUE THREAD

**Issue by redactedscribe** [JackFred2/EyeSpy#4]
**Is your feature request related to a problem? Please describe.**
It would be nice if we could bind Eye Spy to its own key rather than repurposing the Swap Items With Offhand action.

**Describe the solution you'd like**
Like some other mods, a section in the Key Binds menu for Eye Spy which lets you bind a key to the ping action. This decouples pinging and swapping items, but they still could be coupled if both assigned to e.g. F, right?

**Describe alternatives you've considered**
Accept the hardcoded coupling.

Thanks!

**Comment by JackFred2** [comment]
Could be done easily enough; I'll have a look tomorrow. It would mean that you need to install Eye Spy on the client to use the keybind however.

**Comment by JackFred2** [comment]
Added for 1.2.0; though due to vanilla limitations I've changed the client-sided keybind to Z as default.
