### ISSUE TITLE
Make last pinged block outline brighter

### ISSUE THREAD

**Issue by redactedscribe** [JackFred2/EyeSpy#5]
**Is your feature request related to a problem? Please describe.**
Sometimes you press F on the wrong block and now you have 3 blocks highlighted, but which 2 did you mean? The timer has to run out before you can assert which 2 using new pings.

**Describe the solution you'd like**
If the last pinged block was always brighter / more saturated or something, then you could re-ping and already pinged block to point to which block you really mean.

Could this brightness / colour be customised? Perhaps it needn't be if the defaults are helpful enough.

**Describe alternatives you've considered**
\-

Thanks!

**Comment by JackFred2** [comment]
Main issue is the entity pings; I can't change the colour outside of the standard 16, and they have to form fit the entity. I also can't change the size of the glowing outline as it's a shader effect.

Block pings can't have a different outline width either but they have full RGB; I can add a slight brightness to the newest ping.

**Comment by redactedscribe** [comment]
I'm not familiar with the workings of Minecraft, but for the entities (I assume NPCs): If one of the 16 colours was always reserved to only be used for the newest ping, then it'd be possible to visually track it. I guess the problem would then be that it'd override the green/red outline which helps to determine friend/foe. What if this reserved colour (e.g. yellow) was only temporary (like 500ms) and then returned to the underlying green/red/etc outline? Might work.

It's a shame that entities and blocks wouldn't share the same visual indication for the newest ping, but perhaps there are upsides to distinguishing both the newest entity and block separately. Some added brightness would be enough for blocks.

**Comment by JackFred2** [comment]
Added for blocks in 1.2.0, entities are unchanged for now.
