### ISSUE TITLE
Enemy single-ping sound could inform ping is red

### ISSUE THREAD

**Issue by redactedscribe** [JackFred2/EyeSpy#6]
**Is your feature request related to a problem? Please describe.**
Pinging an enemy is the same sound as single-pinged blocks, despite the enemy being outlined in red.

**Describe the solution you'd like**
Perhaps an intermediary warning sound should be introduced to total 3:

- Single ping on any block or friendly.
- **New:** Single ping on enemy: Not as alarming as a danger ping but more than a neutral ping.
- Double ping on block or enemy (danger ping).

Either that or (option to?) make a single ping on an enemy the danger sound by default.

Benefit is that you don't have to rely on visually checking whether the single-ping is a block or enemy. Likely beneficial too in time restricted moments.

**Describe alternatives you've considered**
Always double-ping enemies.

Thanks!

**Comment by JackFred2** [comment]
I've changed the ping sound for enemies to a higher pitched version of the warning sound, which is distinct from the regular sound.
