### ISSUE TITLE
Distance on pinged blocks/NPCs

### ISSUE THREAD

**Issue by redactedscribe** [JackFred2/EyeSpy#7]
**Is your feature request related to a problem? Please describe.**

Pings without using the Spyglass can lack context at longer distances.

I'm using Eye Spy and [Ping Wheel](https://modrinth.com/mod/ping-wheel) as they do related things but with some overlap (pinging). If Eye Spy also had distance optionally displayed on pings, Ping Wheel would have less reason to be installed.

Ideally I could just use one mod, but Ping Wheel also allows pinging dropped items and I doubt implementing everything it can do is a goal. With that being said, there is an argument to be made for having only the one ultimate ping mod for Fabric. The [Ping](https://www.curseforge.com/minecraft/mc-mods/ping) mod for Forge has some neat gesturing features too (mine/look here etc).

**Describe the solution you'd like**

Ping and show distance above (or below?) block/NPC in the colour of the ping (neutral/danger).

Depending how fancy you want to get:

- Could be implemented so that when turning to look away from a pinged object, the distance clings to the edge of the screen as you rotate.
- Could have option to not show distance on pings if distance is within X blocks/metres of the player's position. Or rather than hiding the distance completely, render a simple marker since the actual distance is less relevant when in the immediate vicinity.

**Describe alternatives you've considered**
Use both mods and deal with their separate key binds and settings.

I realise I've made a number of FRs, and I don't expect them all to be fulfilled straight away. I hope they help with your inspiration to continue adding features.

Thanks!

**Comment by JackFred2** [comment]
Pinging Item Entities can be done, that's a 1 line change to the entity filter.

Distance text is also doable, would currently need a little adjustment to the ping management o seperate them between players. Similar to the FOV issue on #8 though I can't really cling them to the edge of the screen; I'll probably have the text not visible unless the cursor is within a cone over the ping.

**Comment by JackFred2** [comment]
Added in 1.3.0
![jtlGPS4Thw](https://github.com/JackFred2/EyeSpy/assets/8350692/6165993d-ccf9-4b68-946e-b4397a9704fe)

**Comment by redactedscribe** [comment]
Thanks for your recent additions @JackFred2, appreciated!
