### ISSUE TITLE
Adjustments to Spyglass' distance text

### ISSUE THREAD

**Issue by redactedscribe** [JackFred2/EyeSpy#8]
**Is your feature request related to a problem? Please describe.**
The Spyglass distance text is a useful addition, however it does take away from the experience of viewing the world in my opinion due to its size and in particular its brightness.

**Describe the solution you'd like**
If the text size / opacity could be adjusted, that would help.

As a suggestion, it might be nice to somewhat lower the default position of the text to retain more of the central view. You can always glance down a little to see the distance of what you're looking at.

**Describe alternatives you've considered**
\-

**Additional context**
\-

Thanks!

**Comment by JackFred2** [comment]
Main issue is accommodating different client FOV settings, which the server isn't told about at any point:

Quake Pro (110)
![Screenshot 2023-12-08 220744](https://github.com/JackFred2/EyeSpy/assets/8350692/23945352-c363-4345-be63-eb8e2a27e516)

30
![Screenshot 2023-12-08 220801](https://github.com/JackFred2/EyeSpy/assets/8350692/305cba09-53dc-451c-9163-8511442fcdb3)

I'll add a server-side text scale setting for now.

**Comment by JackFred2** [comment]
Added for 1.2.0
